(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const levels=[
 {name:'幸運初轉',goal:180,spins:10,count:5,lines:1,rule:'認識三連線'},
 {name:'甜蜜連線',goal:230,spins:10,count:6,lines:1,rule:'累積甜蜜分數'},
 {name:'角色宇宙',goal:280,spins:11,count:8,lines:1,rule:'更多 Freen 登場'},
 {name:'Fluffy 百搭',goal:340,spins:11,count:8,lines:1,wild:true,rule:'狗狗可代替任何角色'},
 {name:'三線閃耀',goal:620,spins:12,count:10,lines:3,wild:true,rule:'開啟三條得分線'},
 {name:'金色時刻',goal:720,spins:12,count:10,lines:3,wild:true,gold:true,rule:'金色角色分數加倍'},
 {name:'翡翠訊號',goal:800,spins:13,count:12,lines:3,wild:true,gold:true,secret:true,rule:'隱藏碎片開始出現'},
 {name:'五星連線',goal:900,spins:13,count:14,lines:5,wild:true,gold:true,secret:true,rule:'五條得分線全開'},
 {name:'Freen Time',goal:1020,spins:14,count:16,lines:5,wild:true,gold:true,secret:true,time:true,rule:'隨機啟動雙倍時間'},
 {name:'二十面相',goal:1100,spins:14,count:20,lines:5,wild:true,gold:true,secret:true,time:true,rule:'20 款 Freen 全登場'},
 {name:'Fluffy Rush',goal:1240,spins:15,count:20,lines:5,wild:true,gold:true,secret:true,time:true,rush:true,rule:'狗狗出現率提升'},
 {name:'宇宙終章',goal:1380,spins:16,count:20,lines:5,wild:true,gold:true,secret:true,time:true,rush:true,rule:'完成最終幸運挑戰'}
];
const lineSets=[[[1,1],[1,1],[1,1]],[[0,0],[0,0],[0,0]],[[2,2],[2,2],[2,2]],[[0,0],[1,1],[2,2]],[[2,2],[1,1],[0,0]]];
let save=readSave(), levelIndex=0, score=0, spins=0, busy=false, noWin=0, attempt=0, sound=save.sound!==false, currentGrid=[];
function readSave(){try{return Object.assign({unlocked:1,stars:Array(12).fill(0),fragments:0,jackpot:false,attempts:Array(12).fill(0),sound:true},JSON.parse(localStorage.getItem('freenFluffyLuckySpinV1')))}catch{return{unlocked:1,stars:Array(12).fill(0),fragments:0,jackpot:false,attempts:Array(12).fill(0),sound:true}}}
function writeSave(){save.sound=sound;localStorage.setItem('freenFluffyLuckySpinV1',JSON.stringify(save))}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
function img(name){return `<img src="${name}" alt="">`}
function symbolHTML(s){let file=s.type==='freen'?`freen-${String(s.id).padStart(2,'0')}.png`:s.type==='fluffy'?'fluffy.png':'secret.png';return `<div class="symbol ${s.type} ${s.gold?'gold':''}">${img(file)}</div>`}
function renderLevels(){const total=save.stars.reduce((a,b)=>a+b,0);$('#totalStars').textContent=total;$('#fragmentCount').textContent=Math.min(6,save.fragments);$('#levelGrid').innerHTML=levels.map((l,i)=>{let open=i<save.unlocked;return `<button class="level-card ${open?'':'locked'}" data-level="${i}" ${open?'':'disabled'}><span class="number">${i+1}</span><span class="name">${l.name}</span><span class="stars">${'★'.repeat(save.stars[i]||0)}${'☆'.repeat(3-(save.stars[i]||0))}</span>${open?'':'<span class="lock-mark">🔒</span>'}</button>`}).join('');$$('.level-card:not(.locked)').forEach(b=>b.onclick=()=>startLevel(+b.dataset.level));$('#continueBtn').classList.toggle('hidden',save.unlocked<=1);$('#continueLevel').textContent=Math.min(save.unlocked,12)}
function renderReels(grid){$('#reels').innerHTML=[0,1,2].map(c=>`<div class="reel">${[0,1,2].map(r=>symbolHTML(grid[r][c])).join('')}</div>`).join('')}
function randomFreen(cfg){return {type:'freen',id:1+Math.floor(Math.random()*cfg.count),gold:cfg.gold&&Math.random()<.07}}
function initialGrid(cfg){return Array.from({length:3},()=>Array.from({length:3},()=>randomFreen(cfg)))}
function startLevel(i){levelIndex=i;const cfg=levels[i];score=0;spins=cfg.spins;noWin=0;attempt=save.attempts[i]||0;busy=false;$('#levelTitle').textContent=`第 ${i+1} 關・${cfg.name}`;$('#levelRule').textContent=cfg.rule;$('#goal').textContent=cfg.goal;$('#score').textContent=0;$('#spins').textContent=spins;$('#progressBar').style.width='0%';$('#message').textContent=attempt>=2?'ENCORE 模式：幸運機率提升！':'按下 SPIN，開始收集幸運！';$('#freenTime').classList.add('hidden');currentGrid=initialGrid(cfg);renderReels(currentGrid);show('game')}
function forceLine(grid,type,id,line=0){const path=lineSets[line];path.forEach(([r],c)=>grid[r][c]=type==='freen'?{type,id:id||1+Math.floor(Math.random()*levels[levelIndex].count)}:{type})}
function makeOutcome(){const cfg=levels[levelIndex], grid=initialGrid(cfg);let roll=Math.random(),forced='';
  const encore=attempt>=2, near=spins<=2&&score<cfg.goal*.72;
  if(cfg.secret&&roll<.0015){forceLine(grid,'secret',0,0);forced='secretJackpot'}
  else if(cfg.secret&&roll<.0095){let cells=[[1,0],[1,1],[1,2]].sort(()=>Math.random()-.5);grid[cells[0][0]][cells[0][1]]={type:'secret'};grid[cells[1][0]][cells[1][1]]={type:'secret'};forced='secretTwo'}
  else if(cfg.secret&&roll<.0345){grid[Math.floor(Math.random()*3)][Math.floor(Math.random()*3)]={type:'secret'};forced='secretOne'}
  else if(cfg.wild&&roll<(cfg.rush?.075:.045)){forceLine(grid,'fluffy',0,Math.floor(Math.random()*cfg.lines));forced='fluffy'}
  else if(near||noWin>=3){forceLine(grid,'freen',1+Math.floor(Math.random()*cfg.count),Math.floor(Math.random()*cfg.lines));forced='help'}
  else if(roll<(encore?.22:.16)){forceLine(grid,'freen',1+Math.floor(Math.random()*cfg.count),Math.floor(Math.random()*cfg.lines));forced='triple'}
  else if(roll<(encore?.52:.44)){const line=Math.floor(Math.random()*cfg.lines),path=lineSets[line],id=1+Math.floor(Math.random()*cfg.count);for(let c=0;c<2;c++){const r=path[c][0];grid[r][c]={type:'freen',id,gold:cfg.gold&&Math.random()<.1}}forced='pair'}
  if(cfg.wild){for(let r=0;r<3;r++)for(let c=0;c<3;c++)if(Math.random()<(cfg.rush?.055:.025)&&grid[r][c].type==='freen')grid[r][c]={type:'fluffy'}}
  return {grid,forced}
}
function evaluate(grid){const cfg=levels[levelIndex];let points=0,winners=[],messages=[];for(let li=0;li<cfg.lines;li++){const path=lineSets[li],syms=path.map(([r],c)=>grid[r][c]);const normals=syms.filter(s=>s.type==='freen');const wilds=syms.filter(s=>s.type==='fluffy').length;const ids=[...new Set(normals.map(s=>s.id))];const counts=ids.map(id=>normals.filter(s=>s.id===id).length);const best=(counts.length?Math.max(...counts):0)+wilds;const allSecret=syms.every(s=>s.type==='secret');const allFluffy=syms.every(s=>s.type==='fluffy');const matched=!syms.some(s=>s.type==='secret')&&(ids.length<=1)&&syms.every(s=>s.type==='fluffy'||s.type==='freen');let won=false;if(allSecret){points+=1200;messages.push('💚 SECRET JACKPOT！');save.jackpot=true;save.fragments=Math.max(6,save.fragments);won=true}else if(allFluffy){points+=500;messages.push('🐶 FLUFFY JACKPOT！');won=true}else if(matched&&normals.length){let p=220;if(syms.some(s=>s.type==='fluffy'))p+=60;if(syms.some(s=>s.gold))p*=2;points+=p;messages.push(syms.some(s=>s.type==='fluffy')?'🐶 Fluffy 幫你三連線！':'✨ Freen 三連線！');won=true}else if(best>=2){let p=55;if(syms.some(s=>s.gold))p*=2;points+=p;messages.push('💕 甜蜜雙連！');won=true}if(won)winners.push(...path.map(([r],c)=>c*3+r))}
  const secretCount=grid.flat().filter(s=>s.type==='secret').length;if(secretCount&&secretCount<3){let old=save.fragments;save.fragments=Math.min(6,save.fragments+secretCount);if(save.fragments>old)messages.push(`💚 翡翠碎片 +${save.fragments-old}`)}return{points,winners:[...new Set(winners)],message:messages.join('　'),secretCount}}
function highlight(indices){const cells=$$('.symbol');indices.forEach(i=>cells[i]?.classList.add('winner'))}
function audio(kind){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=audio.ctx||(audio.ctx=new A());if(ctx.state==='suspended')ctx.resume();const notes=kind==='win'?[523,659,784]:kind==='jackpot'?[523,659,784,1047]:kind==='spin'?[160,130]:[220,180];notes.forEach((f,i)=>{let o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==='spin'?'square':'sine';o.frequency.value=f;g.gain.setValueAtTime(.001,ctx.currentTime+i*.08);g.gain.exponentialRampToValueAtTime(.13,ctx.currentTime+i*.08+.01);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+i*.08+.15);o.connect(g).connect(ctx.destination);o.start(ctx.currentTime+i*.08);o.stop(ctx.currentTime+i*.08+.17)})}
function spin(){if(busy||spins<=0)return;busy=true;spins--;$('#spins').textContent=spins;$('#spinBtn').disabled=true;$('#reels').classList.add('spinning');audio('spin');let ticks=0,timer=setInterval(()=>{renderReels(initialGrid(levels[levelIndex]));$('#reels').classList.add('spinning');if(++ticks>=7){clearInterval(timer);finishSpin()}},75)}
function finishSpin(){const cfg=levels[levelIndex],out=makeOutcome();currentGrid=out.grid;renderReels(currentGrid);const ev=evaluate(currentGrid);let multiplier=cfg.time&&Math.random()<(cfg.rush?.2:.14)?2:1;if(multiplier===2){$('#freenTime').classList.remove('hidden');setTimeout(()=>$('#freenTime').classList.add('hidden'),1100)}ev.points*=multiplier;score+=ev.points;$('#score').textContent=score;$('#progressBar').style.width=Math.min(100,score/cfg.goal*100)+'%';highlight(ev.winners);if(ev.points){noWin=0;$('#message').textContent=(ev.message||'✨ 幸運得分！')+(multiplier===2?'　×2！':'');audio(ev.points>=500?'jackpot':'win')}else{noWin++;$('#message').textContent=noWin>=3?'幸運正在靠近，下一轉有保底！':'再轉一次，幸運正在路上！'}writeSave();setTimeout(()=>{busy=false;$('#spinBtn').disabled=false;if(spins<=0)endLevel()},650)}
function starsFor(score,goal){return score>=goal*1.6?3:score>=goal*1.25?2:score>=goal?1:0}
function endLevel(){const cfg=levels[levelIndex],stars=starsFor(score,cfg.goal),pass=stars>0;save.attempts[levelIndex]=(save.attempts[levelIndex]||0)+1;if(pass){save.stars[levelIndex]=Math.max(save.stars[levelIndex]||0,stars);save.unlocked=Math.max(save.unlocked,Math.min(12,levelIndex+2))}writeSave();$('#resultEmoji').textContent=pass?(stars===3?'🏆':'✨'):'💪';$('#resultTitle').textContent=pass?'過關！':'差一點點！';$('#resultText').textContent=pass?(levelIndex===11?'12 關完成！你收集了整個 Freen 宇宙。':'下一關已解鎖，想拿更多星也可以再挑戰！'):(save.attempts[levelIndex]>=2?'ENCORE 幸運模式已開啟，下次會更容易連線！':'再試一次，連續沒中會自動啟動保底。');$('#resultStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#finalScore').textContent=score;$('#nextBtn').classList.toggle('hidden',!pass||levelIndex===11);show('result');audio(pass?'jackpot':'lose')}
function renderCollection(){let n=Math.min(6,save.fragments);$('#gemSlots').innerHTML=Array.from({length:6},(_,i)=>`<span class="gem-slot ${i<n?'on':''}">${i<n?'💚':'◇'}</span>`).join('');$('#collectionHint').textContent=n>=6?'翡翠隱藏版已解鎖！':`再收集 ${6-n} 枚碎片，即可解鎖完整隱藏圖。`;$('#secretCard').classList.toggle('locked',n<6);$('#secretBadge').classList.toggle('hidden',!save.jackpot);show('collection')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1300)}
$('#startBtn').onclick=()=>{renderLevels();show('levels')};$('#continueBtn').onclick=()=>startLevel(Math.min(save.unlocked-1,11));$$('[data-home]').forEach(b=>b.onclick=()=>show('home'));$('#backLevels').onclick=()=>{renderLevels();show('levels')};$('#spinBtn').onclick=spin;$('#nextBtn').onclick=()=>startLevel(levelIndex+1);$('#retryBtn').onclick=()=>startLevel(levelIndex);$('#chooseBtn').onclick=()=>{renderLevels();show('levels')};$('#collectionBtn').onclick=renderCollection;$('#collectionBack').onclick=()=>{renderLevels();show('levels')};$$('.sound-btn').forEach(b=>b.onclick=()=>{sound=!sound;writeSave();$$('.sound-btn').forEach(x=>x.textContent=sound?'♪':'×');toast(sound?'聲音已開啟':'聲音已關閉')});
renderLevels();$$('.sound-btn').forEach(x=>x.textContent=sound?'♪':'×');
})();
